In [1]:
lst=[1,2,3,4,5,6]
print(lst)

[1, 2, 3, 4, 5, 6]


In [4]:
import numpy as np
arr=np.array(lst, dtype=int)
print(arr)

[1 2 3 4 5 6]


In [5]:
print(type(arr))
print(len(arr))
print(arr.ndim)
print(arr.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [7]:
arr1=arr.reshape(3,2)
print(arr1)
print(arr1.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [9]:
arr2=arr.reshape(2,-1)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [13]:
lst1=[2,3,4,5,6]
lst2=[3,4,5,6,7]

mul_arr=np.array((lst1,lst2)) # we provide list or tuple of list as input to array
print(mul_arr),

print(mul_arr.shape)

[[2 3 4 5 6]
 [3 4 5 6 7]]
(2, 5)


In [14]:
a=np.array([[2,3],[3,4],[5,6]])
print(a.shape)

(3, 2)


In [16]:
#to reshape ndarray
a.shape=(2,3)
print(a)

[[2 3 3]
 [4 5 6]]


In [19]:
b=a.reshape(3,2)
print(b)

[[2 3]
 [3 4]
 [5 6]]


In [20]:
#an array of evenly spaced members
a=np.arange(12)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1


In [24]:
b=a.reshape(3,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]


In [28]:
print(a+b)
print(np.add(b,a))

[[[ 0  1  2  3  4  5  6  7  8  9 10 11]
  [ 1  2  3  4  5  6  7  8  9 10 11 12]
  [ 2  3  4  5  6  7  8  9 10 11 12 13]
  [ 3  4  5  6  7  8  9 10 11 12 13 14]]

 [[ 4  5  6  7  8  9 10 11 12 13 14 15]
  [ 5  6  7  8  9 10 11 12 13 14 15 16]
  [ 6  7  8  9 10 11 12 13 14 15 16 17]
  [ 7  8  9 10 11 12 13 14 15 16 17 18]]

 [[ 8  9 10 11 12 13 14 15 16 17 18 19]
  [ 9 10 11 12 13 14 15 16 17 18 19 20]
  [10 11 12 13 14 15 16 17 18 19 20 21]
  [11 12 13 14 15 16 17 18 19 20 21 22]]]
[[[ 0  1  2  3  4  5  6  7  8  9 10 11]
  [ 1  2  3  4  5  6  7  8  9 10 11 12]
  [ 2  3  4  5  6  7  8  9 10 11 12 13]
  [ 3  4  5  6  7  8  9 10 11 12 13 14]]

 [[ 4  5  6  7  8  9 10 11 12 13 14 15]
  [ 5  6  7  8  9 10 11 12 13 14 15 16]
  [ 6  7  8  9 10 11 12 13 14 15 16 17]
  [ 7  8  9 10 11 12 13 14 15 16 17 18]]

 [[ 8  9 10 11 12 13 14 15 16 17 18 19]
  [ 9 10 11 12 13 14 15 16 17 18 19 20]
  [10 11 12 13 14 15 16 17 18 19 20 21]
  [11 12 13 14 15 16 17 18 19 20 21 22]]]


In [32]:
print(a-b)
print(np.subtract(b,a))

[[[  0   1   2   3   4   5   6   7   8   9  10  11]
  [ -1   0   1   2   3   4   5   6   7   8   9  10]
  [ -2  -1   0   1   2   3   4   5   6   7   8   9]
  [ -3  -2  -1   0   1   2   3   4   5   6   7   8]]

 [[ -4  -3  -2  -1   0   1   2   3   4   5   6   7]
  [ -5  -4  -3  -2  -1   0   1   2   3   4   5   6]
  [ -6  -5  -4  -3  -2  -1   0   1   2   3   4   5]
  [ -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4]]

 [[ -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3]
  [ -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2]
  [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1]
  [-11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0]]]
[[[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11]
  [  1   0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10]
  [  2   1   0  -1  -2  -3  -4  -5  -6  -7  -8  -9]
  [  3   2   1   0  -1  -2  -3  -4  -5  -6  -7  -8]]

 [[  4   3   2   1   0  -1  -2  -3  -4  -5  -6  -7]
  [  5   4   3   2   1   0  -1  -2  -3  -4  -5  -6]
  [  6   5   4   3   2   1   0  -1  -2  -3  -4  -5]
  [ 

In [37]:
print(a*b)
print(np.multiply(b,a))

[[[  0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   1   2   3   4   5   6   7   8   9  10  11]
  [  0   2   4   6   8  10  12  14  16  18  20  22]
  [  0   3   6   9  12  15  18  21  24  27  30  33]]

 [[  0   4   8  12  16  20  24  28  32  36  40  44]
  [  0   5  10  15  20  25  30  35  40  45  50  55]
  [  0   6  12  18  24  30  36  42  48  54  60  66]
  [  0   7  14  21  28  35  42  49  56  63  70  77]]

 [[  0   8  16  24  32  40  48  56  64  72  80  88]
  [  0   9  18  27  36  45  54  63  72  81  90  99]
  [  0  10  20  30  40  50  60  70  80  90 100 110]
  [  0  11  22  33  44  55  66  77  88  99 110 121]]]
[[[  0   0   0   0   0   0   0   0   0   0   0   0]
  [  0   1   2   3   4   5   6   7   8   9  10  11]
  [  0   2   4   6   8  10  12  14  16  18  20  22]
  [  0   3   6   9  12  15  18  21  24  27  30  33]]

 [[  0   4   8  12  16  20  24  28  32  36  40  44]
  [  0   5  10  15  20  25  30  35  40  45  50  55]
  [  0   6  12  18  24  30  36  42  48  54  60  66]
  [ 

In [40]:
print(a.dot(b))
print(np.dot(b,a))

ValueError: shapes (12,) and (3,4,1) not aligned: 12 (dim 0) != 4 (dim 1)

In [43]:
print(b/a)
print(np.divide(a,b))

[[[        nan  0.          0.          0.          0.
    0.          0.          0.          0.          0.
    0.          0.        ]
  [        inf  1.          0.5         0.33333333  0.25
    0.2         0.16666667  0.14285714  0.125       0.11111111
    0.1         0.09090909]
  [        inf  2.          1.          0.66666667  0.5
    0.4         0.33333333  0.28571429  0.25        0.22222222
    0.2         0.18181818]
  [        inf  3.          1.5         1.          0.75
    0.6         0.5         0.42857143  0.375       0.33333333
    0.3         0.27272727]]

 [[        inf  4.          2.          1.33333333  1.
    0.8         0.66666667  0.57142857  0.5         0.44444444
    0.4         0.36363636]
  [        inf  5.          2.5         1.66666667  1.25
    1.          0.83333333  0.71428571  0.625       0.55555556
    0.5         0.45454545]
  [        inf  6.          3.          2.          1.5
    1.2         1.          0.85714286  0.75        0.66666667
    

<ipython-input-43-0ebd707bbb79>:1: RuntimeWarning: divide by zero encountered in true_divide
  print(b/a)
<ipython-input-43-0ebd707bbb79>:1: RuntimeWarning: invalid value encountered in true_divide
  print(b/a)
<ipython-input-43-0ebd707bbb79>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(a,b))
<ipython-input-43-0ebd707bbb79>:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.divide(a,b))


In [47]:
print(b)
print(np.sum(b))

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]]
66


In [48]:
print(np.sum(b, axis=0)) #compute sum of each column

[[12]
 [15]
 [18]
 [21]]


In [49]:
print(np.sum(b, axis=1)) #compute sum of each row

[[ 6]
 [22]
 [38]]
